export let foodTypes = [
  'Dim Sum',
  'Ramen',
  'Buffet',
  'Korean BBQ',
  'Jajangmyeon',
  'Kimchi Soup',
  'Bibimbap',
  'Chicken Rice',
  'Char Kway Teow',
  'Hokkien Mee',
  'Claypot Rice',
  'Congee',
  'Fish n Chips',
  'Fish Soup',
  'Fried Chicken',
  'Prata',
  'Curry',
  'Hor Fun',
  'Biryani',
  'Indian Curry',
  'Mee Goreng',
  'Rojak',
  'Mee Siam',
  'Laksa',
  'Lor Mee',
  'Sushi',
  'Tendon',
  'Japanese Don',
  'Shabu Shabu',
  'Sukiyaki',
  'Kway Chap',
  'Lor Mee',
  'Pad Thai',
  'Mee Rebus',
  'Murtabak',
  'Green Curry',
  'Pho',
  'Pasta',
  'Prawn Mee',
  'Pizza',
  'Roast Duck',
  'Roti John',
  'Satay',
  'Soy Sauce Chicken',
  'Mala',
  'Taiwanese',
  'Wonton Mee',
  'Xiao Long Bao',
  'Yong Tau Foo',
  'Zi Char',
  'Steak',
  'Vegetarian',
  'Bak Kut Teh',
  'Burgers',
  'Mookata',
  'Pasta',
  'Pizza',
  'Ramen',
  'Sandwiches',
];

export let dessertTypes = [
  'Waffles',
  'Ice Cream',
  'Bingsoo',
];

export let areas = [
  'Alexandra',
  'Aljunied',
  'Amoy Street',
  'Ang Mo Kio',
  'Balestier',
  'Bartley',
  'Bayfront',
  'Beach Road',
  'Beauty World',
  'Bedok',
  'Bedok Reservoir',
  'Bencoolen',
  'Bishan',
  'Boat Quay',
  'Boon Keng',
  'Boon Lay',
  'Botanic Gardens',
  'Braddell',
  'Bras Basah',
  'Buangkok',
  'Bugis',
  'Bukit Batok',
  'Bukit Gombak',
  'Bukit Merah',
  'Bukit Panjang',
  'Bukit Timah',
  'Buona Vista',
  'Central, Singapore',
  'Changi',
  'Changi Airport',
  'China Square Central',
  'Chinatown',
  'Chinese Garden',
  'Chip Bee Gardens',
  'Choa Chu Kang',
  'Circular Road',
  'City Hall',
  'Clarke Quay',
  'Clementi',
  'Club Street',
  'Commonwealth',
  'Coronation',
  'Dakota',
  'Dempsey',
  'Dhoby Ghaut',
  'Dover',
  'Downtown',
  'Duxton',
  'East Coast Parkway',
  'East, Singapore',
  'Esplanade',
  'Eunos',
  'Everton Park',
  'Expo',
  'Farrer Park',
  'Farrer Road',
  'Fort Canning',
  'Gardens by the Bay',
  'Geylang',
  'Geylang Bahru',
  'Great World',
  'Haji Lane',
  'Harbourfront',
  'Hillview',
  'Holland Village',
  'Hougang',
  'Jalan Besar',
  'Jalan Kayu',
  'Jalan Riang',
  'Joo Chiat',
  'Jurong East',
  'Jurong West',
  'Kaki Bukit',
  'Kallang',
  'Katong',
  'Kembangan',
  'Kent Ridge',
  'Khatib',
  'King Albert Park',
  'Kovan',
  'Labrador',
  'Lakeside',
  'Lavender',
  'Little India',
  'Lorong Kilat',
  'Macpherson',
  'Marina Bay',
  'Marina Square',
  'Marine Parade',
  'Marymount',
  'Maxwell',
  'Millenia Walk',
  'Mountbatten',
  'Newton',
  'North Bridge Road',
  'North East, Singapore',
  'North, Singapore',
  'Novena',
  'Old Airport Road',
  'One North',
  'Orchard',
  'Outram Park',
  'Pasir Panjang',
  'Pasir Ris',
  'Paya Lebar',
  'Portsdown',
  'Potong Pasir',
  'Promenade',
  'Punggol',
  'Punggol Waterway',
  'Queenstown',
  'Raffles Place',
  'Rangoon Road',
  'Redhill',
  'River Valley',
  'Robertson Quay',
  'Rochor',
  'Seletar',
  'Sembawang',
  'Sengkang',
  'Sentosa',
  'Serangoon',
  'Serangoon Gardens',
  'Shenton Way',
  'Siglap',
  'Simei',
  'Simpang Bedok',
  'Sixth Avenue',
  'Somerset',
  'Stadium',
  'Stevens',
  'Tai Seng',
  'Tampines',
  'Tanah Merah',
  'Tanglin',
  'Tanjong Katong',
  'Tanjong Pagar',
  'Telok Ayer',
  'Telok Blangah',
  'Thomson',
  'Tiong Bahru',
  'Toa Payoh',
  'Tuas',
  'Upper Bukit Timah',
  'Upper East Coast Road',
  'West Coast',
  'West, Singapore',
  'Woodlands',
  'Yio Chu Kang',
  'Yishun',
];
